export const StoryType = {
    LINE: "LINE",
    CHALLENGE_PROMPT: "CHALLENGE_PROMPT",
    ARRANGE: "ARRANGE",
    POINT_TO_PHRASE: "POINT_TO_PHRASE",
    MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
    MATCH: "MATCH"
}